# Generated by Django 3.0.3 on 2020-07-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Message',
        ),
    ]
